---
title: "dataTidying"
author: "Sarah"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_libraries, message =FALSE, warning=FALSE, echo = FALSE}
library(dplyr)
library(tidyr)

```

# load and tidy data
```{r load_data}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"), stringsAsFactors = FALSE)
```

Change from wide to long form, delete a few unnecessary cols, rename
```{r select }
catch_df<-catch_df %>%
  select(-All, -notesRegCode) %>%
  gather(key = "Species", value = catch, -Region, -Year) %>%
  rename(catch_thousands = catch)
```

A not-run example ofr how to go from long to wide
```{r To_WidewSpread, eval = FALSE}
catch_df %>%
  spread(key = "Species", value = catch)
```


Fixing some variables
```{r fix_Error_new_var}
catch_df <- catch_df %>%
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands)) %>%
  mutate(catch_thousands = as.integer(catch_thousands)) %>%
  mutate(catch = catch_thousands*1000)
```

# Analysis
chinook catch by 

```{r summarize}
annual_catch <- catch_df %>%
  filter(Species == "Chinook") %>%
  group_by(Year) %>%
  summarize(meanCatch = mean(catch)) %>%
  arrange(desc(meanCatch))

head(annual_catch, 30)
```

filterign
```{r}
Chinook<-catch_df %>%
  filter(Species == Chinook)

```

